# Generated by Django 3.2.7 on 2023-01-08 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gig_images')),
                ('location', models.CharField(max_length=5000)),
                ('phone', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=50000)),
                ('description', models.CharField(max_length=500000)),
                ('price', models.IntegerField(default=0)),
                ('delivery_time', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Website Development', 'Website Development'), ('Graphics and Design', 'Graphics and Design'), ('Writing and Translation', 'Writing and Translation'), ('Video and Animation', 'Video and Animation'), ('Programming and Tech', 'Programming and Tech'), ('Business', 'Business'), ('Digital Marketing', 'Digital Marketing')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
