# Generated by Django 3.2.7 on 2023-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_gigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='maximum_rate',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='starting_rate',
            field=models.IntegerField(default=0),
        ),
    ]
