# Generated by Django 3.2.7 on 2023-01-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20230108_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='response_time',
            field=models.IntegerField(default=1),
        ),
    ]
