# Generated by Django 3.2.7 on 2023-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='gig_pk',
            field=models.IntegerField(default=0),
        ),
    ]
