# Generated by Django 3.2.7 on 2023-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20230111_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
