# Generated by Django 3.2.7 on 2023-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20230111_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
