# Generated by Django 3.2.7 on 2023-01-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_userprofile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='response_time',
            field=models.IntegerField(default=1),
        ),
    ]
