# Generated by Django 3.2.7 on 2023-01-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_userprofile_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
