# Generated by Django 3.2.7 on 2023-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_userprofile_is_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='maximum_rate',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='response_time',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='starting_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
