# Generated by Django 3.2.7 on 2023-02-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20230117_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_freelancer',
            new_name='is_company',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
