# Generated by Django 3.2.7 on 2023-02-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_company_address_userprofile_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='category',
            field=models.CharField(max_length=500),
        ),
    ]
