# Generated by Django 3.2.7 on 2023-03-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50000)),
                ('answer', models.CharField(default='', max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.question')),
            ],
        ),
    ]
