# Generated by Django 3.2.7 on 2023-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='status',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
