# Generated by Django 3.2.7 on 2023-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_saved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
