# Generated by Django 4.1.2 on 2023-03-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_saved_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gigs',
            options={'verbose_name': 'Post'},
        ),
    ]
