# Generated by Django 4.1.2 on 2023-03-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_gigs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'verbose_name': 'Application'},
        ),
    ]
