# Generated by Django 3.2.7 on 2023-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_userprofile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admission_no',
            field=models.IntegerField(default=0),
        ),
    ]
