from django.urls import path
from . import views 
# from django.conf.urls import url

urlpatterns = [
    path('',views.homepage,name = "homepage"),
    path('home/',views.homepage1,name = "home"),
    path('register/', views.register,name='register' ),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('checkLogin/', views.checkLogin, name = "checkLogin"),
    path('checkSignup/', views.checkSignup,name = 'checkSignup'),
    path('checkUsername/',views.checkUsername,name = "checkUsername"),
    path('postGig/',views.checkUsername,name = "checkUsername"),
    path('post/',views.post,name = "post"),
    path('save/',views.save,name = "save"),
    path('gigView/<int:pk>',views.gigView,name = "gigView"),
    path('delete/<int:pk>',views.delete,name = "delete"),
    path('error/',views.error,name = "error"),
    path('saved/',views.saved,name = "saved"),
    path('gigs/',views.gigs,name = "gigs"),
    path('sendMsg/',views.sendMsg,name = "sendMsg"),
    path('sendMsg1/',views.sendMsg1,name = "sendMsg1"),
    path('showMessages/',views.showMessages,name = "showMessages"),
    path('profileView/<int:pk>',views.profileView,name = "profileView"),
    path('search/',views.search,name = "search"),
    path('editAccount/',views.editAccount,name = "editAccount"),
    path('deleteUser/<int:pk>',views.deleteUser,name = "deleteUser"),
    path('editPost/<int:pk>',views.editPost,name = "editPost"),
    path('freelancers/',views.freelancers,name = "freelancers"),
    path('showLogin/',views.showLogin,name = "showLogin"),
    path('showSignupNormal/',views.showSignupNormal,name = "signup"),
    path('registerNormal/',views.registerNormal,name = "registerNormal"),
    path('createPost/',views.createPost,name = "createPost"),
    path('editGig/<int:pk>',views.editGig,name = "editGig"),
    path('upload/',views.upload,name = "upload"),
    path('mocktest/',views.mocktest,name = "mocktest"),
    path('getResult/',views.getResult,name = "getResult"),
    path('companySignup/',views.companySignup,name = "companySignup"),
    path('companyRegister/',views.companyRegister,name = "companyRegister"),
    path('interview/',views.interview,name = "interview"),
    path('resume/',views.resume,name = "resume"),
    path('uploadVideo/',views.uploadVideo,name = "uploadVideo"),
    path('application/',views.application,name = "application"),
]